name: webrtc_utils
version: 0.2.1
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Provides a set of classes and concepts for clients or servers that can be used to build applications or games utilizing WebRTC.
homepage: https://github.com/roberthartung/webrtc_utils/
environment:
  sdk: <=1.10.0
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  chrome: '>=0.6.5 <0.7.0'
transformers:
- chrome
- $dart2js:
    csp: true
